export interface Backtest {
    id: number;
    name: string;
    user_id: number;
    status: 'pending' | 'running' | 'completed' | 'failed';
    progress: number;
    max_stocks_to_hold: number;
    worst_rank_held: number;
    rebalance_frequency: 'weekly' | 'monthly';
    rebalance_day: number;
    weightage: 'equal_weight' | 'equal_weight_rebalanced' | 'inverse_volatility';
    cash_call: 'no_cash_call' | 'cash_call_if_not_enough_stocks' | 'full_cash_below_index_dma' | 'only_exits_below_index_dma' | 'allocate_to_gold_below_index_dma' | 'only_exits_allocate_to_gold_below_index_dma';
    cash_call_index: string;
    cash_return_rate: number;
    initial_capital: number;
    started_at: string | null;
    completed_at: string | null;
    error_message: string | null;
    index: string;
    sort_by: string;
    sort_direction: string;
    median_volume_one_year: number;
    minimum_return_one_year: number;
    apply_ma: boolean;
    above_ma_200: boolean;
    above_ma_100: boolean;
    above_ma_50: boolean;
    above_ma_20: boolean;
    below_ma_200: boolean;
    below_ma_100: boolean;
    below_ma_50: boolean;
    below_ma_20: boolean;
    apply_ema: boolean;
    above_ema_200: boolean;
    above_ema_100: boolean;
    above_ema_50: boolean;
    above_ema_20: boolean;
    below_ema_200: boolean;
    below_ema_100: boolean;
    below_ema_50: boolean;
    below_ema_20: boolean;
    away_from_high_one_year: number;
    away_from_high_all_time: number;
    positive_days_percent_one_year: number;
    positive_days_percent_nine_months: number;
    positive_days_percent_six_months: number;
    positive_days_percent_three_months: number;
    positive_days_percent_one_months: number;
    circuits_one_year: number;
    circuits_nine_months: number;
    circuits_six_months: number;
    circuits_three_months: number;
    circuits_one_months: number;
    marketcap_from: number;
    marketcap_to: number;
    apply_pe: boolean;
    price_to_earnings_from: number;
    price_to_earnings_to: number;
    series_eq: boolean;
    series_be: boolean;
    ignore_above_beta: number;
    price_from: number;
    price_to: number;
    apply_filters_on: string;
    apply_factor_two: boolean;
    factor_two_sort_by: string;
    factor_two_sort_direction: string;
    apply_factor_three: boolean;
    factor_three_sort_by: string;
    factor_three_sort_direction: string;
    apply_custom_filter_one: boolean;
    custom_filter_one_value_one: string;
    custom_filter_one_operator: string;
    custom_filter_one_value_two: string;
    apply_custom_filter_two: boolean;
    custom_filter_two_value_one: string;
    custom_filter_two_operator: string;
    custom_filter_two_value_two: string;
    apply_custom_filter_three: boolean;
    custom_filter_three_value_one: string;
    custom_filter_three_operator: string;
    custom_filter_three_value_two: string;
    apply_custom_filter_four: boolean;
    custom_filter_four_value_one: string;
    custom_filter_four_operator: string;
    custom_filter_four_value_two: string;
    apply_custom_filter_five: boolean;
    custom_filter_five_value_one: string;
    custom_filter_five_operator: string;
    custom_filter_five_value_two: string;
    created_at: string;
    updated_at: string;
}
