export interface BacktestNseInstrumentViewResource {
    id: number;
    symbol: string;
    name: string;
    close_adjusted: number;
    high_one_year: number;
    away_from_high_one_year: string;
    high_all_time: number;
    away_from_high_all_time: string;
    volatility_one_year: number;
    volatility_nine_months: number;
    volatility_six_months: number;
    volatility_three_months: number;
    volatility_one_months: number;
    absolute_return_one_year: string;
    absolute_return_nine_months: string;
    absolute_return_six_months: string;
    absolute_return_three_months: string;
    absolute_return_one_months: string;
    return_twelve_minus_one_months: string;
    return_twelve_minus_two_months: string;
    sharpe_return_one_year: string;
    sharpe_return_nine_months: string;
    sharpe_return_six_months: string;
    sharpe_return_three_months: string;
    sharpe_return_one_months: string;
    rsi_one_year: number | string;
    rsi_nine_months: number | string;
    rsi_six_months: number | string;
    rsi_three_months: number | string;
    rsi_one_months: number | string;
    ma_200: number;
    ma_100: number;
    ma_50: number;
    ma_20: number;
    ema_200: number;
    ema_100: number;
    ema_50: number;
    ema_20: number;
    positive_days_percent_one_year: string;
    positive_days_percent_nine_months: string;
    positive_days_percent_six_months: string;
    positive_days_percent_three_months: string;
    positive_days_percent_one_months: string;
    circuits_one_year: number;
    circuits_nine_months: number;
    circuits_six_months: number;
    circuits_three_months: number;
    circuits_one_months: number;
    price_to_earnings: number;
    marketcap: string;
    series: string;
    beta: number;
    median_volume_one_year: number;
    indices: string[];
}
